
icons:
  ai:           
  android:      
  apple:        
  audio:        
  c:            
  conf:         
  cpp:          
  css:          
  doc:          
  docker:       
  ebook:        
  env:          
  epub:         
  font:         
  git:          
  go:           
  html:         
  image:        
  java:         
  js:           
  json:         
  jsx:          
  lock:         
  log:          
  md:           
  npmignore:    
  pdf:          
  php:          
  py:           
  rb:           
  react:        ﰆ
  rss:          
  rust:         
  sass:         
  shell:        
  svg: 
  swift: ﯣ
  symlink: 
  test: 
  toml: 
  ts:           
  txt:          
  unknown: 
  video:        
  vim:          
  windows:      
  xls:          
  xml:          
  yarn.lock:    
  yml:          
  zip:          
aliases:
  apk:              android
  gradle:           android
  ds_store:         apple
  localized:        apple
  flac:             audio
  m4a:              audio
  mp3:              audio
  ogg:              audio
  wav:              audio
  editorconfig:     conf
  scss:             css
  docx:             doc
  gdoc:             doc
  dockerfile:       docker
  mobi:             ebook
  eot:              font
  otf:              font
  ttf:              font
  woff:             font
  woff2:            font
  .gitconfig:        git
  .gitignore:        git
  bmp:              image
  gif:              image
  ico:              image
  jpeg:             image
  jpg:              image
  odg:              image
  png:              image
  pxm:              image
  tiff:             image
  webp:             image
  jar:              java
  tsx:              jsx
  license:          md
  ipynb:            py
  pyc:              py
  bash:             shell
  bash_history:     shell
  bash_profile:     shell
  bashrc:           shell
  fish:             shell
  sh:               shell
  zsh:              shell
  zsh-theme:        shell
  zshrc:            shell
  avi:              video
  flv:              video
  mkv:              video
  mov:              video
  mp4:              video
  ogv:              video
  webm:             video
  bat:              windows
  exe:              windows
  ini:              windows
  csv:              xls
  gsheet:           xls
  xlsx:             xls
  yaml:             yml
  gz:               zip
  rar:              zip
  tar:              zip
  tgz:              zip
