on:
  pull_request:
  push:
    branches:
      - main

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Cargo.lock checksum
        id: checksum
        run: echo "::set-output name=checksum::$(md5sum Cargo.lock | cut -d ' ' -f 1)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-cache-dependencies-${{ steps.checksum.outputs.checksum }}
          restore-keys: ${{ runner.os }}-build-cache-dependencies
      - name: Run all tests
        run: cargo test --no-fail-fast -- --test-threads=1 --nocapture
